### ISSUE TITLE
Follow me Algorithm on MiR250 using ROS

### ISSUE THREAD

**Issue by R0b0tics123** [DFKI-NI/mir_robot#100]
Hi everyone, I just began a project which tasked me to develop a follow me feature on MiR250. Just wondering on how i can get started with this. I am relatively new to ROS and would appreciate some guidance. basically the desired goal of the follow me algorithm is for the MiR to be able to follow another moving object (ie, another MiR or a human). 

Also would using a RGB camera be enough or would we need a LiDAR sensor.

Appreciate any help on this thanks.

**Comment by mintar** [comment]
There are plenty of packages that track and/or follow people, based on 2D LiDARs, 3D LiDARs, RGB-D (3D) cameras and monocular RGB cameras. Here are some examples:

* https://github.com/spencer-project/spencer_people_tracking
* https://wiki.ros.org/people
* https://github.com/koide3/monocular_person_following

The MiR robot already comes equipped with two 2D LiDARs that you can use for person following. You could maybe add an additional cheap RGB-D camera like a Intel Realsense D435 or D455 and you should be good to go. No need for an expensive 3D LiDAR.
