### ISSUE TITLE
Decrypt Error logs of MiR 200

### ISSUE THREAD

**Issue by Hardikrathod01** [DFKI-NI/mir_robot#104]
Since this repository supports MiR robots in ROS I thought I will ask the question here. 
In MiR robots in a web interface there is a function of getting error logs. These error logs are encrypted and I am not aware of how to decrypt these logs. 

If anyone happen to know how to decrypt these logs please provide instructions on how to do that. 
Basically these logs are encrypted gpg files. There is no information what is the key to decrypt these files.

Thanks in advance.

**Comment by mintar** [comment]
I don't know how to decrypt those logs. However, I suspect that the purpose of this function in the web interface is just to get logs that you can send to the manufacturer, and that they are encrypted to protect your privacy when you send them by email. You can probably get the same information via other options on the web interface or via the `diagnostics` and `diagnostics_agg` topics.

**Comment by Hardikrathod01** [comment]
Yes, I also had this impression that those downloaded logs gives the same information as web interface. 
Thank you for the answer.
