### ISSUE TITLE
a warn

### ISSUE THREAD

**Issue by lvjihui** [DFKI-NI/mir_robot#107]
[ WARN] [1648279251.216721898, 505.301000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame odom at time 505.486000 according to authority unknown_publisher

Any clues about this warning? 
THANK YOU

**Comment by matthias-mayr** [comment]
You can take a look at https://github.com/dfki-ric/mir_robot/issues/88. It seems to be the same issue
