### ISSUE TITLE
Compatibility with version 2.8.x broken?

### ISSUE THREAD

**Issue by moooeeeep** [DFKI-NI/mir_robot#118]
Now that the message types have changed with the recent commits, we would expect compatibility with version 2.8 to be at least partially broken, right?

We might need to adjust the README, or point people to a compatibility tag/branch that still have an older version.

**Comment by mintar** [comment]
I haven't tested it with 2.8.3.1 again, but when I added the new messages, I was trying to be careful to break as little as possible. :)

The default configuration should still be working on 2.8.3.1. The only thing that doesn't work any more is BMSData, but that isn't published by the mir_driver by default (without commenting in a line) anyway.
