### ISSUE TITLE
Error mir_gazebo mir_maze_world.launch

### ISSUE THREAD

**Issue by nbsnbs** [DFKI-NI/mir_robot#123]
Hey ı can try this repository and completly manuel and start but error dont working 

full installed and  ı can try this comman : roslaunch mir_gazebo mir_maze_world.launch 

but error with me console and don't load urdf / gazebo robot model 

[ERROR] [1673735199.523148929]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/left_wheel_joint
[ERROR] [1673735199.525153121]: No p gain specified for pid. Namespace: /gazebo_ros_control/pid_gains/right_wheel_joint

ubuntu@ubuntu:~$ roslaunch mir_gazebo mir_maze_world.launch
... logging to /home/ubuntu/.ros/log/7d87276e-945a-11ed-a8e7-c959f80a5624/roslaunch-ubuntu-67171.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:39215/

SUMMARY
========

CLEAR PARAMETERS
 * /ekf_localization_node/

PARAMETERS
 * /ekf_localization_node/acceleration_gains: [0.8, 0.0, 0.0, 0...
 * /ekf_localization_node/acceleration_limits: [1.3, 0.0, 0.0, 0...
 * /ekf_localization_node/base_link_frame: base_footprint
 * /ekf_localization_node/control_config: [True, False, Fal...
 * /ekf_localization_node/control_timeout: 0.2
 * /ekf_localization_node/debug: False
 * /ekf_localization_node/debug_out_file: /path/to/debug/fi...
 * /ekf_localization_node/deceleration_gains: [1.0, 0.0, 0.0, 0...
 * /ekf_localization_node/deceleration_limits: [1.3, 0.0, 0.0, 0...
 * /ekf_localization_node/frequency: 40
 * /ekf_localization_node/imu0: imu_data
 * /ekf_localization_node/imu0_config: [False, False, Fa...
 * /ekf_localization_node/imu0_differential: False
 * /ekf_localization_node/imu0_nodelay: False
 * /ekf_localization_node/imu0_queue_size: 10
 * /ekf_localization_node/imu0_relative: True
 * /ekf_localization_node/imu0_remove_gravitational_acceleration: False
 * /ekf_localization_node/initial_estimate_covariance: [100.0, 0, 0, 0, ...
 * /ekf_localization_node/map_frame: map
 * /ekf_localization_node/odom0: odom
 * /ekf_localization_node/odom0_config: [False, False, Fa...
 * /ekf_localization_node/odom0_differential: False
 * /ekf_localization_node/odom0_nodelay: False
 * /ekf_localization_node/odom0_queue_size: 10
 * /ekf_localization_node/odom0_relative: False
 * /ekf_localization_node/odom_frame: odom
 * /ekf_localization_node/print_diagnostics: True
 * /ekf_localization_node/process_noise_covariance: [0.05, 0, 0, 0, 0...
 * /ekf_localization_node/publish_acceleration: False
 * /ekf_localization_node/publish_tf: True
 * /ekf_localization_node/sensor_timeout: 0.1
 * /ekf_localization_node/stamped_control: False
 * /ekf_localization_node/transform_time_offset: 0.0
 * /ekf_localization_node/transform_timeout: 0.0
 * /ekf_localization_node/two_d_mode: True
 * /ekf_localization_node/use_control: False
 * /ekf_localization_node/world_frame: odom
 * /gazebo/enable_ros_network: True
 * /joint_state_controller/publish_rate: 50
 * /joint_state_controller/type: joint_state_contr...
 * /joint_state_publisher/rate: 200.0
 * /joint_state_publisher/source_list: ['mir/joint_states']
 * /mobile_base_controller/angular/z/has_acceleration_limits: True
 * /mobile_base_controller/angular/z/has_velocity_limits: True
 * /mobile_base_controller/angular/z/max_acceleration: 2.5
 * /mobile_base_controller/angular/z/max_velocity: 1.5
 * /mobile_base_controller/base_frame_id: base_footprint
 * /mobile_base_controller/cmd_vel_timeout: 0.5
 * /mobile_base_controller/enable_odom_tf: False
 * /mobile_base_controller/left_wheel: left_wheel_joint
 * /mobile_base_controller/linear/x/has_acceleration_limits: True
 * /mobile_base_controller/linear/x/has_velocity_limits: True
 * /mobile_base_controller/linear/x/max_acceleration: 2.0
 * /mobile_base_controller/linear/x/max_velocity: 1.0
 * /mobile_base_controller/odom_frame_id: odom
 * /mobile_base_controller/pose_covariance_diagonal: [1e-05, 1e-05, 10...
 * /mobile_base_controller/publish_rate: 41.2
 * /mobile_base_controller/right_wheel: right_wheel_joint
 * /mobile_base_controller/twist_covariance_diagonal: [0.1, 0.1, 100000...
 * /mobile_base_controller/type: diff_drive_contro...
 * /mobile_base_controller/wheel_radius_multiplier: 1.0
 * /mobile_base_controller/wheel_separation_multiplier: 1.0
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.15.15
 * /rqt_robot_steering/default_topic: cmd_vel
 * /rqt_robot_steering/default_vw_max: 1.5
 * /rqt_robot_steering/default_vw_min: -1.5
 * /rqt_robot_steering/default_vx_max: 1.0
 * /rqt_robot_steering/default_vx_min: -1.0
 * /use_sim_time: True

NODES
  /
    b_rep117_laser_filter (mir_driver/rep117_filter.py)
    b_scan_relay (topic_tools/relay)
    controller_spawner (controller_manager/spawner)
    ekf_localization_node (robot_localization/ekf_localization_node)
    f_rep117_laser_filter (mir_driver/rep117_filter.py)
    f_scan_relay (topic_tools/relay)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rqt_robot_steering (rqt_robot_steering/rqt_robot_steering)
    spawn_maze (gazebo_ros/spawn_model)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [67181]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7d87276e-945a-11ed-a8e7-c959f80a5624
process[rosout-1]: started with pid [67194]
started core service [/rosout]
process[gazebo-2]: started with pid [67202]
process[gazebo_gui-3]: started with pid [67207]
process[spawn_urdf-4]: started with pid [67209]
process[controller_spawner-5]: started with pid [67213]
process[ekf_localization_node-6]: started with pid [67214]
process[joint_state_publisher-7]: started with pid [67215]
process[robot_state_publisher-8]: started with pid [67220]
process[rqt_robot_steering-9]: started with pid [67223]
process[b_scan_relay-10]: started with pid [67224]
process[f_scan_relay-11]: started with pid [67225]
process[b_rep117_laser_filter-12]: started with pid [67234]
process[f_rep117_laser_filter-13]: started with pid [67235]
process[spawn_maze-14]: started with pid [67239]
[INFO] [1673735193.272112, 0.000000]: Waiting for /clock to be available...
[INFO] [1673735193.704838, 0.000000]: Loading model XML from file /home/ubuntu/test_ws/src/mir_robot/mir_gazebo/sdf/maze/model.sdf
[INFO] [1673735193.711899, 0.000000]: Waiting for service /gazebo/spawn_sdf_model
[ INFO] [1673735195.970863166]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1673735195.977844955]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1673735196.239129133]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1673735196.243535853]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[INFO] [1673735197.667402, 0.000000]: Calling service /gazebo/spawn_sdf_model
[ INFO] [1673735197.670842777]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1673735198.594372652]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1673735198.595675268]: Starting Laser Plugin (ns = /)
[ INFO] [1673735198.598758410]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1673735199.147216419]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1673735199.147395614]: Starting Laser Plugin (ns = /)
[ INFO] [1673735199.149245099]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1673735199.396560450]: Loading gazebo_ros_control plugin
[ INFO] [1673735199.397206778]: Starting gazebo_ros_control plugin in namespace: /
[ INFO] [1673735199.398329712]: gazebo_ros_control plugin is waiting for model URDF in parameter [robot_description] on the ROS param server.
**_### [ERROR] [1673735199.523148929]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/left_wheel_joint
[ERROR] [1673735199.525153121]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/right_wheel_joint_**
[ INFO] [1673735199.532842115]: Loaded gazebo_ros_control.
[INFO] [1673735199.907157, 0.000000]: Spawn status: SpawnModel: Successfully spawned entity
[ INFO] [1673735199.926402199]: Physics dynamic reconfigure ready.
[spawn_urdf-4] process has finished cleanly
log file: /home/ubuntu/.ros/log/7d87276e-945a-11ed-a8e7-c959f80a5624/spawn_urdf-4*.log
[spawn_maze-14] process has finished cleanly
log file: /home/ubuntu/.ros/log/7d87276e-945a-11ed-a8e7-c959f80a5624/spawn_maze-14*.log
context mismatch in svga_surface_destroy
context mismatch in svga_surface_destroy

**Comment by mintar** [comment]
Thanks for the bug report!

These errors are "normal" and can be ignored. I'm sorry about that, but we cannot avoid producing these errors.

I have added documentation explaining why to the README: https://github.com/dfki-ric/mir_robot#gazebo-prints-errors-no-p-gain-specified-for-pid
