### ISSUE TITLE
Error with Running the World Warehouse Gazebo World

### ISSUE THREAD

**Issue by odai93sh** [DFKI-NI/mir_robot#135]
I'm currently facing an error while trying to run the "World Warehouse" Gazebo world.

rospack] Error: package 'aws_robomaker_small_warehouse_world' not found
... logging to /home/user/.ros/log/2fa11f70-b9f0-11ee-a77f-01e8d9c80b51/roslaunch-user-virtual-machine-522095.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://user-virtual-machine:43663/

SUMMARY
========

CLEAR PARAMETERS
 * /ekf_localization_node/

PARAMETERS
 * /ekf_localization_node/acceleration_gains: [0.8, 0.0, 0.0, 0...
 * /ekf_localization_node/acceleration_limits: [1.3, 0.0, 0.0, 0...
 * /ekf_localization_node/base_link_frame: base_footprint
 * /ekf_localization_node/control_config: [True, False, Fal...
 * /ekf_localization_node/control_timeout: 0.2
 * /ekf_localization_node/debug: False
 * /ekf_localization_node/debug_out_file: /path/to/debug/fi...
 * /ekf_localization_node/deceleration_gains: [1.0, 0.0, 0.0, 0...
 * /ekf_localization_node/deceleration_limits: [1.3, 0.0, 0.0, 0...
 * /ekf_localization_node/frequency: 40
 * /ekf_localization_node/imu0: imu_data
 * /ekf_localization_node/imu0_config: [False, False, Fa...
 * /ekf_localization_node/imu0_differential: False
 * /ekf_localization_node/imu0_nodelay: False
 * /ekf_localization_node/imu0_queue_size: 10
 * /ekf_localization_node/imu0_relative: True
 * /ekf_localization_node/imu0_remove_gravitational_acceleration: False
 * /ekf_localization_node/initial_estimate_covariance: [100.0, 0, 0, 0, ...
 * /ekf_localization_node/map_frame: map
 * /ekf_localization_node/odom0: odom
 * /ekf_localization_node/odom0_config: [False, False, Fa...
 * /ekf_localization_node/odom0_differential: False
 * /ekf_localization_node/odom0_nodelay: False
 * /ekf_localization_node/odom0_queue_size: 10
 * /ekf_localization_node/odom0_relative: False
 * /ekf_localization_node/odom_frame: odom
 * /ekf_localization_node/print_diagnostics: True
 * /ekf_localization_node/process_noise_covariance: [0.05, 0, 0, 0, 0...
 * /ekf_localization_node/publish_acceleration: False
 * /ekf_localization_node/publish_tf: True
 * /ekf_localization_node/sensor_timeout: 0.1
 * /ekf_localization_node/stamped_control: False
 * /ekf_localization_node/transform_time_offset: 0.0
 * /ekf_localization_node/transform_timeout: 0.0
 * /ekf_localization_node/two_d_mode: True
 * /ekf_localization_node/use_control: False
 * /ekf_localization_node/world_frame: odom
 * /gazebo/enable_ros_network: True
 * /joint_state_controller/publish_rate: 50
 * /joint_state_controller/type: joint_state_contr...
 * /joint_state_publisher/rate: 200.0
 * /joint_state_publisher/source_list: ['mir/joint_states']
 * /mobile_base_controller/angular/z/has_acceleration_limits: True
 * /mobile_base_controller/angular/z/has_velocity_limits: True
 * /mobile_base_controller/angular/z/max_acceleration: 2.5
 * /mobile_base_controller/angular/z/max_velocity: 1.5
 * /mobile_base_controller/base_frame_id: base_footprint
 * /mobile_base_controller/cmd_vel_timeout: 0.5
 * /mobile_base_controller/enable_odom_tf: False
 * /mobile_base_controller/left_wheel: left_wheel_joint
 * /mobile_base_controller/linear/x/has_acceleration_limits: True
 * /mobile_base_controller/linear/x/has_velocity_limits: True
 * /mobile_base_controller/linear/x/max_acceleration: 2.0
 * /mobile_base_controller/linear/x/max_velocity: 1.0
 * /mobile_base_controller/odom_frame_id: odom
 * /mobile_base_controller/pose_covariance_diagonal: [1e-05, 1e-05, 10...
 * /mobile_base_controller/publish_rate: 41.2
 * /mobile_base_controller/right_wheel: right_wheel_joint
 * /mobile_base_controller/twist_covariance_diagonal: [0.1, 0.1, 100000...
 * /mobile_base_controller/type: diff_drive_contro...
 * /mobile_base_controller/wheel_radius_multiplier: 1.0
 * /mobile_base_controller/wheel_separation_multiplier: 1.0
 * /robot_description: <?xml version="1....
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /rqt_robot_steering/default_topic: cmd_vel
 * /rqt_robot_steering/default_vw_max: 1.5
 * /rqt_robot_steering/default_vw_min: -1.5
 * /rqt_robot_steering/default_vx_max: 1.0
 * /rqt_robot_steering/default_vx_min: -1.0
 * /use_sim_time: True

NODES
  /
    b_rep117_laser_filter (mir_driver/rep117_filter.py)
    b_scan_relay (topic_tools/relay)
    controller_spawner (controller_manager/spawner)
    ekf_localization_node (robot_localization/ekf_localization_node)
    f_rep117_laser_filter (mir_driver/rep117_filter.py)
    f_scan_relay (topic_tools/relay)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rqt_robot_steering (rqt_robot_steering/rqt_robot_steering)
    spawn_urdf (gazebo_ros/spawn_model)

auto-starting new master
process[master]: started with pid [527722]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to d84fd95e-b9f5-11ee-a77f-01e8d9c80b51
process[rosout-1]: started with pid [527732]
started core service [/rosout]
process[gazebo-2]: started with pid [527740]
process[gazebo_gui-3]: started with pid [527744]
process[spawn_urdf-4]: started with pid [527750]
process[controller_spawner-5]: started with pid [527751]
process[ekf_localization_node-6]: started with pid [527752]
process[joint_state_publisher-7]: started with pid [527753]
process[robot_state_publisher-8]: started with pid [527754]
process[rqt_robot_steering-9]: started with pid [527755]
process[b_scan_relay-10]: started with pid [527760]
process[f_scan_relay-11]: started with pid [527765]
process[b_rep117_laser_filter-12]: started with pid [527771]
process[f_rep117_laser_filter-13]: started with pid [527783]
[INFO] [1706017605.742347, 0.000000]: Controller Spawner: Waiting for service controller_manager/load_controller
[ INFO] [1706017606.086611407]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1706017606.088705931]: waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
[ INFO] [1706017606.216987718]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1706017606.219236740]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1706017606.738825214]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1706017606.764948445]: Physics dynamic reconfigure ready.
[ INFO] [1706017607.505671023]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1706017607.505781637]: Starting Laser Plugin (ns = /)
[ INFO] [1706017607.509244201]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1706017607.686855777]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1706017607.686917342]: Starting Laser Plugin (ns = /)
[ INFO] [1706017607.689548433]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1706017607.868495846]: Loading gazebo_ros_control plugin
[ INFO] [1706017607.868896226]: Starting gazebo_ros_control plugin in namespace: /
[ INFO] [1706017607.869977839]: gazebo_ros_control plugin is waiting for model URDF in parameter [robot_description] on the ROS param server.
[ERROR] [1706017607.989644120]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/left_wheel_joint
[ERROR] [1706017607.990568884]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/right_wheel_joint
[ INFO] [1706017607.995506559]: Loaded gazebo_ros_control.
[INFO] [1706017608.158537, 0.000000]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1706017608.162147, 0.000000]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1706017608.165236, 0.000000]: Loading controller: joint_state_controller
[INFO] [1706017608.174793, 0.000000]: Loading controller: mobile_base_controller
[ INFO] [1706017608.188194212]: Controller state will be published at 41.2Hz.
[ INFO] [1706017608.189431126]: Wheel separation will be multiplied by 1.
[ INFO] [1706017608.190228656]: Left wheel radius will be multiplied by 1.
[ INFO] [1706017608.190287292]: Right wheel radius will be multiplied by 1.
[ INFO] [1706017608.191168390]: Velocity rolling window size of 10.
[ INFO] [1706017608.192161441]: Velocity commands will be considered old if they are older than 0.5s.
[ INFO] [1706017608.192575421]: Allow mutiple cmd_vel publishers is enabled
[ INFO] [1706017608.193585515]: Base frame_id set to base_footprint
[ INFO] [1706017608.194387062]: Odometry frame_id set to odom
[ INFO] [1706017608.195144956]: Publishing to tf is disabled
[ INFO] [1706017608.209137156]: left wheel to origin: 0,0.2015, 0.1
[ INFO] [1706017608.209223176]: right wheel to origin: 0,-0.2015, 0.1
[ INFO] [1706017608.209496005]: Odometry params : wheel separation 0.403, left wheel radius 0.1, right wheel radius 0.1
[ INFO] [1706017608.212386215]: Adding left wheel with joint name: left_wheel_joint and right wheel with joint name: right_wheel_joint
[ INFO] [1706017608.223555561]: Dynamic Reconfigure:
DynamicParams:
	Odometry parameters:
		left wheel radius multiplier: 1
		right wheel radius multiplier: 1
		wheel separation multiplier: 1
	Publication parameters:
		Publish executed velocity command: disabled
		Publication rate: 41.2
		Publish frame odom on tf: disabled
[INFO] [1706017608.226982, 0.000000]: Controller Spawner: Loaded controllers: joint_state_controller, mobile_base_controller
[spawn_urdf-4] process has finished cleanly
log file: /home/user/.ros/log/d84fd95e-b9f5-11ee-a77f-01e8d9c80b51/spawn_urdf-4*.log

**Comment by mintar** [comment]
See the README:

```
cd <your catkin workspace>
git clone -b ros1 https://github.com/aws-robotics/aws-robomaker-small-warehouse-world.git
catkin build
```

**Comment by odai93sh** [comment]
I have already did all the steps in README, but despite that, i continue to encounter the same error

**Comment by mintar** [comment]
It's working:

```
mguenther@mguenther-p15-u:~$ sudo apt install ros-noetic-mir-robot
mguenther@mguenther-p15-u:~$ source /opt/ros/noetic/setup.zsh
mguenther@mguenther-p15-u:~$ mkdir -p ros/noetic/tmp/src
mguenther@mguenther-p15-u:~$ cd ros/noetic/tmp/src
mguenther@mguenther-p15-u:~/ros/noetic/tmp/src$ git clone -b ros1 https://github.com/aws-robotics/aws-robomaker-small-warehouse-world.git
Cloning into 'aws-robomaker-small-warehouse-world'...
remote: Enumerating objects: 391, done.
remote: Counting objects: 100% (67/67), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 391 (delta 43), reused 35 (delta 35), pack-reused 324
Receiving objects: 100% (391/391), 9.18 MiB | 7.70 MiB/s, done.
Resolving deltas: 100% (200/200), done.

mguenther@mguenther-p15-u:~/ros/noetic/tmp/src$ cd ..

mguenther@mguenther-p15-u:~/ros/noetic/tmp$ catkin init
Initializing catkin workspace in `/home/mguenther/ros/noetic/tmp`.
-------------------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/noetic
Workspace:                   /home/mguenther/ros/noetic/tmp
-------------------------------------------------------------------
Build Space:       [missing] /home/mguenther/ros/noetic/tmp/build
Devel Space:       [missing] /home/mguenther/ros/noetic/tmp/devel
Install Space:      [unused] /home/mguenther/ros/noetic/tmp/install
Log Space:         [missing] /home/mguenther/ros/noetic/tmp/logs
Source Space:       [exists] /home/mguenther/ros/noetic/tmp/src
DESTDIR:            [unused] None
-------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
-------------------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------------------

mguenther@mguenther-p15-u:~/ros/noetic/tmp$ catkin b
==> Expanding alias 'b' from 'catkin b' to 'catkin build'
-------------------------------------------------------------------
Profile:                     default
Extending:             [env] /opt/ros/noetic
Workspace:                   /home/mguenther/ros/noetic/tmp
-------------------------------------------------------------------
Build Space:        [exists] /home/mguenther/ros/noetic/tmp/build
Devel Space:        [exists] /home/mguenther/ros/noetic/tmp/devel
Install Space:      [unused] /home/mguenther/ros/noetic/tmp/install
Log Space:         [missing] /home/mguenther/ros/noetic/tmp/logs
Source Space:       [exists] /home/mguenther/ros/noetic/tmp/src
DESTDIR:            [unused] None
-------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
-------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------------------
Buildlisted Packages:        None
Skiplisted Packages:         None
-------------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
-------------------------------------------------------------------
[build] Found 1 packages in 0.0 seconds.
[build] Updating package table.
Starting  >>> catkin_tools_prebuild
Finished  <<< catkin_tools_prebuild                              [ 1.5 seconds ]
Starting  >>> aws_robomaker_small_warehouse_world
Finished  <<< aws_robomaker_small_warehouse_world                [ 1.8 seconds ]
[build] Summary: All 2 packages succeeded!
[build]   Ignored:   None.
[build]   Warnings:  None.
[build]   Abandoned: None.
[build]   Failed:    None.
[build] Runtime: 3.3 seconds total.
[build] Note: Workspace packages have changed, please re-source setup files to use them.

mguenther@mguenther-p15-u:~/ros/noetic/tmp$ source devel/setup.zsh

mguenther@mguenther-p15-u:~/ros/noetic/tmp$ roslaunch mir_gazebo mir_empty_world.launch \
        world_name:=$(rospack find aws_robomaker_small_warehouse_world)/worlds/no_roof_small_warehouse.world \
        mir_type:=mir_250
```
