### ISSUE TITLE
register new sensor

### ISSUE THREAD

**Issue by odai93sh** [DFKI-NI/mir_robot#138]
Hello,
am trying to add a new radar sensor (https://github.com/uos/rmagine_gazebo_plugins)
I've followed all the instruction on the new sensor documentation, and it works with examples.
When I tried to implement it with mir_250, it dosen't works, because one step is necessary: "register a new sensor in gzserver", will you please advice me where should i register this sensor?

the command is:

```xml
<node name="gazebo" pkg="gazebo_ros" type="gzserver" args="-s librmagine_embree_sensors_gzregister.so" output="screen" /> -->
  <!-- <node name="gazebo_gui" pkg="gazebo_ros" type="gzclient" output="screen" if="$(arg gui)" />
```

thanks in advance.

**Comment by mintar** [comment]
Sounds like a you should open this issue in [rmagine_gazebo_plugins](https://github.com/uos/rmagine_gazebo_plugins), not here.

@aock: Any ideas?

**Comment by amock** [comment]
I agree. I don't believe that this particular robot model prevents the radar simulation from working. So @odai93sh, I suggest you to open an issue in [rmagine_gazebo_plugins](https://github.com/uos/rmagine_gazebo_plugins) or in [radarays_gazebo_plugins](https://github.com/uos/radarays_gazebo_plugins) instead. In addition, I would need more information on what exactly you changed in the MIR files to get the simulation running.

**Comment by mintar** [comment]
Closing this issue. Please reopen at one of @aock's repositories.
