### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by e-compton** [DFKI-NI/mir_robot#2]
Hi I'm trying to install the binary version of this package, but can't seem to find it in the ubuntu or debian package repositories. Is there a repository that needs to be added to my source list?

Have tried:
```
sudo apt install ros-indigo-mir-robot
sudo apt install ros-jade-mir-robot
```

**Comment by mintar** [comment]
Yes, you should run this:

```
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
sudo apt-get update -qq
```

I'll update the README accordingly. At the moment, only `indigo` and `kinetic` have binary packages for `mir_robot`.

**Comment by Hazem9806** [comment]
@mintar 
Is it available for ROS noetic?
I tried 
`sudo apt install ros-noetic-mir-robot`
but it doesn't work

**Comment by mintar** [comment]
Yes, it is available. Your command is also correct, I just verified that it works. Make sure that you're running Ubuntu 20.04, that you've enabled the apt repository and that you've run `sudo apt update` before.
