### ISSUE TITLE
tf_remap of a frame not working

### ISSUE THREAD

**Issue by christenbc** [DFKI-NI/mir_robot#22]
I am trying to remap the name of a tf like follows:
```
<node pkg="tf" type="tf_remap" name="tf_remapper" output="screen">
  <rosparam param="mappings">
    [{old: camera_floor_depth_optical_frame, new: /camera_depth_optical_frame}]
  </rosparam>
</node>
```
The problem comes that the original tf name remain the same.. why is this happening?

**Comment by mintar** [comment]
The tf_remap node subscribes to the topic /tf_old and publishes on /tf, so you have to remap the /tf topic of the mir_bridge node to /tf_old. Also see:

* http://wiki.ros.org/Remapping%20Arguments
* http://wiki.ros.org/roslaunch/XML/remap
* https://answers.ros.org/question/9248/how-do-you-remap-a-topic/
* https://answers.ros.org/question/216582/how-to-use-tf_remap/

This is not a problem with this package, so I'm closing the issue. Please ask general questions at https://answers.ros.org/ .
