### ISSUE TITLE
ROS bridge

### ISSUE THREAD

**Issue by christenbc** [DFKI-NI/mir_robot#25]
I have a question:
Is it possible to make the ROS bridge just for certain terminals and not for all of them?

**Comment by mintar** [comment]
What do you mean by terminals? Do you mean ROS topics?

**Comment by christenbc** [comment]
No, I mean Command Prompt Windows, in linux aka terminals. I figured out that after executing your ROS bridge if I use the export ROS ip commands, then in such terminal will connect directly to the robot topics

**Comment by mintar** [comment]
All nodes need to connect to the same ROS master, if that's what you're asking.
