### ISSUE TITLE
Clicking on a goal in RViz and sending the MiR to that goal

### ISSUE THREAD

**Issue by rsr152** [DFKI-NI/mir_robot#29]
Hi all,

This situation is similar to #21 but that issue has been closed, hence posting here (if there is a way to re-open closed issues please let me know.  I would rather not post the same request in multiple threads)

I am seeing the same behavior as in #21 -- the (real) robot does not move after clicking on a destination in RViz. All the settings, publications and subscriptions are in line with what @mintar has outlined above (screenshots attached). The map displayed in RViz as well as the position of the robot in the map are accurate.

The only step I did differently was:
In RViz, I clicked "2D Nav Goal", then click on the map, as I have been doing in Gazebo.
I have not yet tried clicking on "2D Pose Estimate" and then clicking on the map because I wanted to be cautious and not have the 65kg robot run crazy in the lab :)

The robot runs fine through the MiR web interface but I don't believe you can change goals on the fly there.
Appreciate any help.  As always, thank you!

--

![Screenshot_2019-05-16_09-21-30](https://user-images.githubusercontent.com/47621008/57874173-d3aaeb00-77c4-11e9-9fab-493b8c1328a0.png)
![Screenshot from 2019-05-16 09-20-17](https://user-images.githubusercontent.com/47621008/57874174-d3aaeb00-77c4-11e9-9a6a-409f5e1c66c7.png)
![Screenshot from 2019-05-16 09-18-28](https://user-images.githubusercontent.com/47621008/57874175-d4438180-77c4-11e9-953a-09f56ac68282.png)
![Screenshot_2019-05-16_09-17-39](https://user-images.githubusercontent.com/47621008/57874176-d4438180-77c4-11e9-84d8-6a46c67134db.png)

**Comment by mintar** [comment]
I've reopened #21 and will close this one.
