### ISSUE TITLE
mir_bridge stays on still waiting for connection to 192.168.12.20

### ISSUE THREAD

**Issue by eduardoruizrz** [DFKI-NI/mir_robot#30]
Hi. While trying this package I faced the constant appearing of the warning: still waiting for connection to 192.168.12.20.
My computer is connected to MiR network, I tried both WiFi and Ethernet.
Do you know what could be the root of the problem? Is it on MiR's side or on mine?
Thanks in advance for the help.

**Comment by mintar** [comment]
Can you ping the IP from your computer? Can you open the web interface at http://192.168.12.20 in a browser? Alternatively, can you open it at http://mir.com? If yes, what is the IP address of mir.com from your computer?

**Comment by eduardoruizrz** [comment]
Thanks for your answer Martin.Yes I could ping the IP, I can access MiR interface in both ways. Furthermore I can export the ROS Master Uri and read from the MiR topics, all this using the IP 192.168.12.20, that's why found it weird that there was this connection issue.

**Comment by blixtdevelopment** [comment]
I am currently having the same problem. I am able to connect to MiR's interface through chrome and I am also able to see all the topics/services/etc. when exporting ROS Master URI. However, rosbridge does not work. 
My ROS version: Melodic
MiR100 software version: 2.3.0
MiR API version: 2.0.0
MiR IP: 192.168.12.20

I have also tried to see if roslibpy could work, but it did not.

**Comment by ben-greenberg** [comment]
I am also experiencing this issue. 

I am trying to test out this package for my MiR500. I am able to ping/connect to the MiR, but the mir_bridge node gets stuck waiting for connection to the robot.

My ROS version: Melodic
MiR500 software version: 2.7.1
MiR IP: 192.168.12.20

**Comment by mintar** [comment]
Hmmm. There seem to be multiple people having this problem. Let's try to narrow this down.

My ROS version: Kinetic
MiR100 software version: 2.3.1
MiR IP: 192.168.12.20

### How to run

```
export ROS_MASTER_URI=http://localhost:11311
roslaunch mir_driver mir.launch
```

This works for me (i.e., I get past the "waiting for connection" message, and I can use `rostopic echo scan` etc.)

### Connection debugging

```
$ nmap -sV 192.168.12.20

Starting Nmap 7.01 ( https://nmap.org ) at 2019-08-07 15:10 CEST
Nmap scan report for 192.168.12.20
Host is up (0.00048s latency).
Not shown: 995 closed ports
PORT     STATE SERVICE VERSION
22/tcp   open  ssh     OpenSSH 7.2p2 Ubuntu 4ubuntu2.1 (Ubuntu Linux; protocol 2.0)
80/tcp   open  http    Apache httpd 2.4.18 ((Ubuntu))
8080/tcp open  http    Apache httpd 2.4.18 ((Ubuntu))
8888/tcp open  http    Werkzeug httpd 0.10.4 (Python 2.7.12)
9090/tcp open  http    Tornado httpd 4.0.2
Service Info: OS: Linux; CPE: cpe:/o:linux:linux_kernel

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 37.07 seconds

# In order to capture the following dump, I put in an `exit()` call in mir_bridge.py so that it exits after establishing the connection. Then I started tcpdump and afterwards mir_bridge.py.
$ sudo tcpdump -s 0 -v -nn -A -i enp2s0 'host 192.168.12.20 && port 9090'
tcpdump: listening on enp2s0, link-type EN10MB (Ethernet), capture size 262144 bytes
17:52:28.599552 IP (tos 0x0, ttl 64, id 60019, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.12.120.46482 > 192.168.12.20.9090: Flags [S], cksum 0x9a0b (incorrect -> 0xfb03), seq 105644737, win 29200, options [mss 1460,sackOK,TS val 679556715 ecr 0,nop,wscale 8], length 0
E..<.s@.@..k...x......#..L........r............
(.6k........
17:52:28.600022 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 60)
    192.168.12.20.9090 > 192.168.12.120.46482: Flags [S.], cksum 0xad2d (correct), seq 1420215024, ack 105644738, win 28960, options [mss 1460,sackOK,TS val 4185603491 ecr 679556715,nop,wscale 7], length 0
E..<..@.@..........x#...T....L....q .-.........
.{=.(.6k....
17:52:28.600060 IP (tos 0x0, ttl 64, id 60020, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.12.120.46482 > 192.168.12.20.9090: Flags [.], cksum 0x9a03 (incorrect -> 0x4ca7), ack 1, win 115, options [nop,nop,TS val 679556715 ecr 4185603491], length 0
E..4.t@.@..r...x......#..L..T......s.......
(.6k.{=.
17:52:28.600262 IP (tos 0x0, ttl 64, id 60021, offset 0, flags [DF], proto TCP (6), length 244)
    192.168.12.120.46482 > 192.168.12.20.9090: Flags [P.], cksum 0x9ac3 (incorrect -> 0x9dde), seq 1:193, ack 1, win 115, options [nop,nop,TS val 679556715 ecr 4185603491], length 192
E....u@.@......x......#..L..T......s.......
(.6k.{=.GET / HTTP/1.1
Upgrade: websocket
Connection: Upgrade
Host: 192.168.12.20:9090
Origin: http://192.168.12.20:9090
Sec-WebSocket-Key: S8MDimtGSEm9xaLaHulK3g==
Sec-WebSocket-Version: 13


17:52:28.600673 IP (tos 0x0, ttl 64, id 7446, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.12.20.9090 > 192.168.12.120.46482: Flags [.], cksum 0x4b6f (correct), ack 193, win 235, options [nop,nop,TS val 4185603491 ecr 679556715], length 0
E..4..@.@..........x#...T....L......Ko.....
.{=.(.6k
17:52:28.601998 IP (tos 0x0, ttl 64, id 7447, offset 0, flags [DF], proto TCP (6), length 181)
    192.168.12.20.9090 > 192.168.12.120.46482: Flags [P.], cksum 0x701f (correct), seq 1:130, ack 193, win 235, options [nop,nop,TS val 4185603493 ecr 679556715], length 129
E.....@.@..O.......x#...T....L......p......
.{=.(.6kHTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: +1/LjDXGuZprJ4T9kS/Mu/PjwEk=


17:52:28.602012 IP (tos 0x0, ttl 64, id 60022, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.12.120.46482 > 192.168.12.20.9090: Flags [.], cksum 0x9a03 (incorrect -> 0x4b5e), ack 130, win 119, options [nop,nop,TS val 679556717 ecr 4185603493], length 0
E..4.v@.@..p...x......#..L..T..r...w.......
(.6m.{=.
17:52:28.898377 IP (tos 0x0, ttl 64, id 60023, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.12.120.46482 > 192.168.12.20.9090: Flags [F.], cksum 0x9a03 (incorrect -> 0x4a35), seq 193, ack 130, win 119, options [nop,nop,TS val 679557013 ecr 4185603493], length 0
E..4.w@.@..o...x......#..L..T..r...w.......
(.7..{=.
17:52:28.898855 IP (tos 0x0, ttl 64, id 7448, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.12.20.9090 > 192.168.12.120.46482: Flags [F.], cksum 0x4897 (correct), seq 130, ack 194, win 235, options [nop,nop,TS val 4185603790 ecr 679557013], length 0
E..4..@.@..........x#...T..r.L......H......
.{>.(.7.
17:52:28.898864 IP (tos 0x0, ttl 64, id 60024, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.12.120.46482 > 192.168.12.20.9090: Flags [.], cksum 0x9a03 (incorrect -> 0x490a), ack 131, win 119, options [nop,nop,TS val 679557014 ecr 4185603790], length 0
E..4.x@.@..n...x......#..L..T..s...w.......
(.7..{>.

# This is while mir_bridge.py is running:
$ sudo netstat -apn | grep 9090
tcp        0      0 192.168.12.120:42014    192.168.12.20:9090      ESTABLISHED 16621/python
```

**Comment by mintar** [comment]
@ben-greenberg: Currently, this repo is only fully compatible with MiR software 2.3.1 and earlier; you'll run into trouble on MiR software 2.7.1. However, this first step (establishing the connection) should work.

Tomorrow I'll try to test it with melodic.

**Comment by mintar** [comment]
I've just tested it successfully on melodic - so it doesn't make a difference whether it's melodic or kinetic.

Everyone who is having problems: could you run the commands from my last comment and paste the results here? I have no clue why your robots behave differently from mine. :)

**Comment by mintar** [comment]
Also make sure that you are *not* using the robot's IP as the ROS master, but the local PC:

```bash
export ROS_MASTER_URI=http://localhost:11311
```

**Comment by eduardoruizrz** [comment]
@mintar I haven't had time to test it, however the IP export could be the issue, as I was exporting the ROS Master from the robot IP and not from my own computer. I'll let you know as soon as I test it. Thanks.

**Comment by Houman-HM** [comment]
Dear @mintar 

I have the same problem connecting to MiR100, software version 2.7.1.
I can ping and connect to the robot through the web interface, however,  it fails to establish connection through ROS Bridge.
This problem has happened recently and I didn't have it before.

I have already tried exporting the ROS_MASTER_URI but no luck.
I was wondering if you could help me solve this problem.
Thanks.

**Comment by liesrock** [comment]
I was able to solve the above issue: it is probably related with the version of the 'websocket-client' python module installed in your system.

In fact debugging the *mir_bridge.py* I found the right place to look at: https://github.com/websocket-client/websocket-client/issues/467

So I decided to switch back to version 0.52.0 of the websocket-client installed in my system (ubuntu 18.04) as described here (https://github.com/websocket-client/websocket-client/issues/467#issuecomment-470881828) :

> ```
> pip uninstall websocket
> pip uninstall websocket-client
> pip install websocket-client==0.52.0
> ```

After this the mir_bridge worked as expected.

**Comment by mintar** [comment]
Thanks for your helpful comment, @liesrock ! I think this might be the solution.

The default version of websocket on Ubuntu 18.04 (when installed via `apt install python-websocket`) is **0.44**.

The default version of websocket on Ubuntu 20.04 (when installed via `apt install python3-websocket`) is **0.53**.

These are the versions that mir_robot expects for melodic and noetic respectively, so you should use them. Of course, if you install stuff using pip, it messes everything up, as usual.

In the `noetic` branch of this repo, I've adapted mir_robot to  websocket versions >= 0.49 a while ago: https://github.com/dfki-ric/mir_robot/commit/27af75a512f204fbc8eb61f1f9f96e0099bde55f

If you for some reason use websocket 0.53, but are *not* using noetic, you should cherry-pick that commit.
