### ISSUE TITLE
Get velocities of left and right wheel

### ISSUE THREAD

**Issue by Floheile** [DFKI-NI/mir_robot#36]
Question:
Is there a way to get the velocities of the left and right wheel from the MiR?

I was thinking the` /joint_states` topic would provide such information, but apparently the fake_mir_joint_publisher.py only publishes zeros.

Thanks for any help in advance!

**Comment by mintar** [comment]
Unfortunately, the MiR does not directly publish the joint states. This is why I hacked together the `fake_mir_joint_publisher.py` (just so we get *any* joint states for all wheels, even if it's just zeroes). It should be possible to subscribe to the `/odom` topic and calculate the wheel velocities from there. The function to calculate the `/odom` information looks something like this: 

https://github.com/ros-controls/ros_controllers/blob/252594832d5e358972a28ceacdc227460ad8c718/diff_drive_controller/src/odometry.cpp#L76-L112

If you write the inverse function of that, you should be able to get the wheel speeds.
