### ISSUE TITLE
[WARN] : topic 'odom_comb' is not published by MIR

### ISSUE THREAD

**Issue by trkygt** [DFKI-NI/mir_robot#37]
Hi,

I have an issue that this is similar to #17 although I am using the newest version mir_robot on MIR100 with 2.0.18. 

In my case, though, when I launch mir.launch there are two warning messages for the unpublished topics: 

- mir_status
- odom_comb

I am not sure if this is related to the other issue I have that is also related to another issue #7. 
Although I update the system time and synchronize the MIR time from the device I have huge delays in tf_monitor. 

And, because of that I can't generate the map in rviz, etc. I would appreciate any help. Thanks!

Best,
Tarik

**Comment by ngwk1** [comment]
Hi, 

I am also facing the same issue. The system runs perfectly on MiR web interface but `mir_driver` is missing both of the topics as you mentioned above. When generating map, it will generate some data occasionally but mostly it would just drop messages for the tf transform. 

I also realized while try to map, it would occassionally show a perfect map exactly the same as the web interface and then fall back to a totally irrelevant map.
