### ISSUE TITLE
Is this the official source code from MiR (the company)?

### ISSUE THREAD

**Issue by kyunghwan** [DFKI-NI/mir_robot#41]
I have simple question, is this the official source code from Mir Robot Company?

**Comment by planthaber** [comment]
No.

This is the code the German Research Center for Artificial Intelligence (DFKI) created to use the MIR Robots with ROS.

I am not the developer but @mintar might tell you more.

**Comment by mintar** [comment]
That's correct. We are not affiliated with MiR (the company), and the code in this repo is not supported by MiR.

**Comment by planthaber** [comment]
@mintar I think it is a good idea to add that to the repository description

**Comment by mintar** [comment]
Done: f6b9a4e61f79f3966cab039f47950cfb628e51f6.

**Comment by planthaber** [comment]
I meant the description for the github repository on the github repository page itself:
Changed it for you ;-) 

    ROS support for the MiR100 Robot. This is a community project to use the MiR Robots with ROS. It is not affiliated with Mobile Industrial Robots.
