### ISSUE TITLE
I need an advice on customizing a MiR platform.

### ISSUE THREAD

**Issue by hayohan39** [DFKI-NI/mir_robot#48]
Hello!
First of all, I am impressed what you have done with MiR100.
I would like to get some advice about building a robot system, If you don't mind.

I am trying to control MiR mobile robot in a custom way and all I got is a REST API documentation.
When I look into it, I cannnot find any GET or POST Encoder, IMU, Laserscan, velocity or something.

How is it possible to make it SLAM or navigating with REST API?
I would like to know how you make a bridge on the mobile robot(which has a driving unit black-boxed ) to your ROS package with REST API.

Thank you!

**Comment by mintar** [comment]
I'm sorry this issue got lost and I didn't reply to it. I'm closing it now due to inactivity. Feel free to reopen (or add a new one) if you want to add something.
