### ISSUE TITLE
Reusability of the code in other MiR models

### ISSUE THREAD

**Issue by BezniF** [DFKI-NI/mir_robot#49]
Hi author, can this package be used also with other MiR models beside the mir100? For example, if i were to change the xacro files to adapt it into the MiR500 model, can i simulate it in Gazebo with this same code?
And, more importantly, can i also connect it to the real robot using the same procedure presented in the README and move it via ROS? Any information on the topic would be very appreciated

**Comment by mintar** [comment]
I haven't tried the MiR500 yet, so I don't know if the ROS interface is the same as the one for the MiR100/MiR200. Please ask Mobile Industrial Robotics (or your distributor).

About the Gazebo simulation: Yes, if you update the xacro files and the [footprint](https://github.com/dfki-ric/mir_robot/blob/7682e991e0efb66b1fcfbf0a4c2b42f9a837235a/mir_navigation/config/move_base_common_params.yaml#L2), the Gazebo simulation should also work for the MiR500.
