### ISSUE TITLE
roslaunch mir_navigation hector_mapping.launch.xml

### ISSUE THREAD

**Issue by FaseehCS** [DFKI-NI/mir_robot#50]
Running the above command gives the following output
SUMMARY
========

PARAMETERS
 * /hector_mapping/advertise_map_service: True
 * /hector_mapping/base_frame: base_footprint
 * /hector_mapping/laser_max_dist: 30.0
 * /hector_mapping/laser_min_dist: 0.4
 * /hector_mapping/laser_z_max_value: 1.0
 * /hector_mapping/laser_z_min_value: -1.0
 * /hector_mapping/map_frame: map
 * /hector_mapping/map_multi_res_levels: 3
 * /hector_mapping/map_pub_period: 2.0
 * /hector_mapping/map_resolution: 0.05
 * /hector_mapping/map_size: 2048
 * /hector_mapping/map_start_x: 0.5
 * /hector_mapping/map_start_y: 0.5
 * /hector_mapping/map_update_angle_thresh: 0.06
 * /hector_mapping/map_update_distance_thresh: 0.4
 * /hector_mapping/map_with_known_poses: False
 * /hector_mapping/odom_frame: odom_comb
 * /hector_mapping/pose_update_topic: poseupdate
 * /hector_mapping/pub_map_odom_transform: True
 * /hector_mapping/pub_map_scanmatch_transform: True
 * /hector_mapping/pub_odometry: False
 * /hector_mapping/scan_subscriber_queue_size: 5
 * /hector_mapping/scan_topic: scan
 * /hector_mapping/sys_msg_topic: syscommand
 * /hector_mapping/tf_map_scanmatch_transform_frame_name: scanmatcher_frame
 * /hector_mapping/update_factor_free: 0.4
 * /hector_mapping/update_factor_occupied: 0.9
 * /hector_mapping/use_tf_pose_start_estimate: False
 * /hector_mapping/use_tf_scan_transformation: True
 * /rosdistro: melodic
 * /rosversion: 1.14.4

NODES
  /
    hector_mapping (hector_mapping/hector_mapping)

ROS_MASTER_URI=http://localhost:11311

ERROR: cannot launch node of type [hector_mapping/hector_mapping]: hector_mapping
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/user/catkin_ws/src
ROS path [2]=/opt/ros/melodic/share
No processes to monitor
shutting down processing monitor...
... shutting down processing monitor complete

I have already sourced the workspace and   ros melodic share. hector_mapping.launch.xml is in the package but the roslaunch is still not finding it. Any solutions?
Thank you

**Comment by mintar** [comment]
Oops, you're right, I forgot to add a dependency. I've fixed that. In the meantime, please run:

```bash
sudo apt install ros-melodic-hector-mapping
```
