### ISSUE TITLE
Manually upgrading the package for compatibility with MiR SW 2.8.*

### ISSUE THREAD

**Issue by BenziF** [DFKI-NI/mir_robot#55]
After reading different issues in this repo, and since ourselves too currently share the same condition as many here, namely we're forced to work on a software version of the MiR robot which is above the supported one (2.3.1), we were interested in manually upgrading the ROS software in order to make it fully compatible with MiR software version 2.8 and  above. 

Many issues were already opened in this regard, our question was, is there a list of steps that you (the code's original developers) would undertake in order to functionally update the ROS code? Since all of the robots in our lab currently work with ROS only, we'd really like to integrate the software in the framework, instead of being forced the REST API.

Thank you very much in advance, I know this isn't easy business

**Comment by mintar** [comment]
Let's continue the discussion in #45, so we have all in one place. I'll write a comment there explaining how you can help!
