### ISSUE TITLE
Publishing on topic /cmd_vel not working

### ISSUE THREAD

**Issue by alibinjunaid** [DFKI-NI/mir_robot#66]
I have followed all the issues related to publishing on the /cmd_vel topic. There is a melodic-2.8 branch for the recent software version on mir but it does not work. Seems like it works on mir SW v2.7.2 but does not work 2.8.3.

What changes in the source code i need to make it work with MiR SW v2.8.3?

Any help or update would be appreciated!

**Comment by mintar** [comment]
I don't have MiR software 2.8.3 available for testing, so I can't help you here. Maybe this is related to #30?

**Comment by liesrock** [comment]
@alibinjunaid you can take a look here: https://github.com/dfki-ric/mir_robot/issues/30#issuecomment-707203907

Thanks to the melodic-2.8 branch everything works as expected.

**Comment by mintar** [comment]
Did this solve your problem, @alibinjunaid ?

**Comment by mintar** [comment]
@liesrock : Can you confirm that this is working for you on MiR version 2.8.3?

**Comment by liesrock** [comment]
@mintar I did the tests with 2.7.9 , but in the near future I will test the above also with 2.8.3
