### ISSUE TITLE
Unable to see all topics?

### ISSUE THREAD

**Issue by LukasLundgren96** [DFKI-NI/mir_robot#69]
I am trying to use the ROS bridge to initiate a docking sequence and can't really figure out how to do it.  However when recording the mir_log topic when docking using the MIR web interface I saw some topics that I could not list using rostopic list. This is a message that uses several topics I cannot list. For instance I can not list /MissionController/prompt_user, /MissionController/goal_position_guid etc. 

"header:
  seq: 2987
  stamp:
    secs: 1602250435
    nsecs: 487521212
  frame_id: "mir"
level: 2
name: "/MissionController"
msg: "ActionHandler Found! - ID: docking Type: DockingAction"
file: "../../src/mirMission/src/mission.cpp"
function: "FindHandlerAndSetParameters"
line: 494
topics: [/rosout, /check_area/polygon, /MissionController/CheckArea/visualization_marker,
  /MissionController/goal_position_guid, /light_cmd, /move_base/goal, /move_base/cancel,
  /tf, /MissionController/prompt_user, /mir_status_msg]"

**Comment by mintar** [comment]
You can add any topics that are missing to this list:

https://github.com/dfki-ric/mir_robot/blob/2229f7dac5ebba671fe1e7b991def80585499a18/mir_driver/nodes/mir_bridge.py#L105

However, I don't think this will let us initiate the docking sequence. Instead, I believe we need to use the REST API. Let's continue the discussion at #74!
