### ISSUE TITLE
"Docking" function of MiR using ROS bridge // Mission command via ROS

### ISSUE THREAD

**Issue by BenziF** [DFKI-NI/mir_robot#72]
Hi everyone, 

for our application, we want to move the MiR 100 robot entirely using ROS. I'm currently trying to implement the same Docking function offered by the MiR firmware, in which enabling "Precision Docking" one can create _precision docking markers_ inside the map and use them inside a mission to precisely align a robot to a desired docking station.

The procedure is portrayed in chapter 5 of https://www.mobile-industrial-robots.com/media/7486/mir-precision-docking-operating-guide_12_en.pdf

My question is, since this doesn't seems really straightforward to manually implement, the easiest way might be to create a mission with precision docking using the MiR proprietary sw and then commanding the mission start from the ROS bridge. Up to now we can move the robot posting on `/cmd_vel` or using `move_base/goal` , but we never tried to start a mission from the ROS node. Is this feature available or is it yet to be implemented?

Thank you a lot in advance for your time and support!

**Comment by mintar** [comment]
I think the best way to implement this is using the REST API. Since #74 is a bit more general, let's continue the discussion over there!
