### ISSUE TITLE
Help with posting to a mission queue 

### ISSUE THREAD

**Issue by michael-chikamchun** [DFKI-NI/mir_robot#75]
Hi,

I am trying to post a move command to the mission queue using the rest api.

What’s I’m trying to do is to try to send the robot to a location p3(guid: mirconst-guid-0000-0001-positions010) and
"mission_id": "abe05a24-3183-11eb-b645-000c29a5725a",
 
The created mission is labelled m1 and position P3. The guids for both mission and position is right.  
 
{
    "mission_id": "abe05a24-3183-11eb-b645-000c29a5725a",
    "parameters": [
        {
            "input_name": "p3",
            "value": "mirconst-guid-0000-0001-positions010"
        }
    ]
}

![image](https://user-images.githubusercontent.com/54597149/101265375-f3419580-3713-11eb-80aa-51ee135540d3.png)

 But i get this 500 internal server error.  Do you know what i may be doing wrong? 
![image](https://user-images.githubusercontent.com/54597149/101265401-37cd3100-3714-11eb-9dac-6c3751da515a.png)

![image](https://user-images.githubusercontent.com/54597149/101265526-305a5780-3715-11eb-8963-30a9818c54b1.png)

Thanks for your help,
Michael

**Comment by mintar** [comment]
The REST API is not supported by this project yet. I haven't used it yet, so I'm afraid I can't help you.
