### ISSUE TITLE
Loading own map wtih multiple robots

### ISSUE THREAD

**Issue by ljaniec** [DFKI-NI/mir_robot#83]
Hi,

This project is a great help in my work, but I am missing maybe something obvious for more experienced ROS/Gazebo users. 

How could I load my own previously prepared in Gazebo map of walls and obstacles (and second one, with virtual obstacles for forbidden areas) for multiple MiR 100's? I have a plan of the floor too for it as a PNG black & white image.

Best regards
Lukasz

**Comment by mintar** [comment]
You're talking about the Gazebo simulation, not the real robots, correct? In that case, you can just give the path to the `map.yaml` files to the `map_file` and `virtual_walls_map_file` arguments of `mir_navigation/launch/start_planner.launch`. Look at `mir_gazebo/maps/maze.yaml` for the format.

**Comment by ljaniec** [comment]
Yes, I meant in Gazebo simulation. I will try your hints and report with its effects later in an edit.

**Comment by mintar** [comment]
Please don't edit, just add a new comment. I don't get email notifications for edits.
