### ISSUE TITLE
Unknown error initiating TCP/IP socket

### ISSUE THREAD

**Issue by brean** [DFKI-NI/mir_robot#86]
Hi.

I noticed that when I call `roslaunch mir_gazebo mir_maze_world.launch` the `spawn_maze` node throws a Traceback during startup when it tries to connect to somewhere. This does not seem to be a problem, the simulation is running anyway but I think it should be fixed.
The traceback reads:
```
Unknown error initiating TCP/IP socket to 8b19b3808422:46969 (http://8b19b3808422:40611/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'
```
and it is logged to your `spawn_maze-14.log`-file.

**Comment by mintar** [comment]
That problem is either fixed in Noetic, or it was a transient problem on your machine. I didn't test in Melodic, but at least for me the problem doesn't occur.
