### ISSUE TITLE
need some data on how to implement virtual wall in costmap do i have to write a plugin for that

### ISSUE THREAD

**Issue by jamesjamal** [DFKI-NI/mir_robot#89]
Want to know how to implement virtual wall

**Comment by mintar** [comment]
1. Create a PNG image for your virtual walls and corresponding YAML file (have a look at this directory: [mir_gazebo/maps](https://github.com/dfki-ric/mir_robot/tree/94dd2d9b3e55ec3dac5f9d63b088beb39c50741e/mir_gazebo/maps)). 
2. `roslaunch mir_navigation start_planner.launch virtual_walls_map_file:=<path to your virtual walls .yaml file>`

**Comment by jamesjamal** [comment]
thanks man i configured maps   for my navigation simulation
