### ISSUE TITLE
the execution can't succeed. 

### ISSUE THREAD

**Issue by marooncn** [DFKI-NI/mir_robot#9]
I do the simulation step by step, but the execution can't succeed as the following:
![peek 2018-12-22 11-33](https://user-images.githubusercontent.com/29606478/50370229-f2260500-05dd-11e9-802c-9524146d0570.gif)
I think there maybe some error in the model or parameter setting, Is it?

**Comment by mintar** [comment]
Thank you for your bug report!

That seems to be a bug in the [eband_local_planner](http://wiki.ros.org/eband_local_planner): It tries to take a shortcut through the wall. I don't know what causes this. You can try one of the other local planners by changing the `local_planner:=eband` parameter. Local planner can be either `dwa`, `eband`, `base`, `teb` or `pose`. However, the other local planners have different problems, and eband is the one that worked best for me.

In general, the local planner is the part of the navigation config that I'm not yet happy with. If you find better parameters for any of the local planners, please let me know.

**Comment by marooncn** [comment]
Hi, @mintar, I change the local planner to dwa, but it still doesn't work:
![peek 2018-12-23 21-38](https://user-images.githubusercontent.com/29606478/50384129-60acb500-06fb-11e9-87e4-9a19e222c5c5.gif)
It seems like two other extension bodies tries to move rather the robot self. So it's judged to stuck while the robot is free.

**Comment by mintar** [comment]
That's weird, I've never seen anything like that. What are those "extension bodies"? Maybe something goes wrong with your simulation of the laser scans.

**Comment by mintar** [comment]
This was probably fixed by #13 .
