### ISSUE TITLE
Can't change resolution of map yaml

### ISSUE THREAD

**Issue by lawrenceztang** [DFKI-NI/mir_robot#93]
I tried to make a custom map, but I found out that when I tried to change the resolution in the map yaml file to something other than .05, I get an error: 
```
[ INFO] [1626805133.713636752, 178.933000000]: Name is SBPLLatticePlanner
terminate called after throwing an instance of 'SBPL_Exception'
  what():  ERROR: failed to read in motion primitive file
```
I don't know what this means or what motion primitive files are, but it seems like something is hard coded to prevent changes in the resolution parameter. I guess I could just change the resolution of the image so that it matches up with the resolution parameter in the yaml?

**Comment by mintar** [comment]
That error comes from `sbpl_lattice_planner`. It means that the motion primitive file (https://github.com/dfki-ric/mir_robot/blob/7d9c72942d512b191f2b326ca89c066710db4e34/mir_navigation/mprim/unicycle_highcost_5cm.mprim) has to match the map resolution (5cm).

You can either:

1. Exchange the mprim file that's loaded [here](https://github.com/dfki-ric/mir_robot/blob/7d9c72942d512b191f2b326ca89c066710db4e34/mir_navigation/launch/move_base.xml#L8) with one for your new map resolution, or:
2. Make sure that the map resolution stays the same (5cm).
