### ISSUE TITLE
Transforms missing Rviz

### ISSUE THREAD

**Issue by azizs1** [DFKI-NI/mir_robot#95]
Hello,

Currently working with a MiR100 with ROS Noetic and an Ubuntu 20.04 PC and while trying to debug why when I publish to move_base_simple/goal, it wasn't actually moving in real life. I noticed when I launched rviz using `rviz -d $(rospack find mir_navigation)/rviz/navigation.rviz`, I received the following:
![rviz](https://user-images.githubusercontent.com/55463731/138005369-bcb8906f-629b-4c44-afa1-64571d6dc4cf.png)

Evidently, some transforms were not being published, so when I ran tf_monitor, I get the following:
![tf_monitor](https://user-images.githubusercontent.com/55463731/138006078-1489fbda-0709-4dc8-ab68-05952606b59b.png)

The /base_footprint is almost exactly 6 hours behind, but my system time and MiR time should be accurate and matching, so I am not really sure what the issue is here. I am a bit new to this whole thing, so if there is anymore information I can provide, please let me know. Thanks in advance!

**Comment by mintar** [comment]
> The /base_footprint is almost exactly 6 hours behind, but my system time and MiR time should be accurate and matching, so I am not really sure what the issue is here.

No, the synchronization between the system time and the MiR time is exactly the problem. The fact that it's almost exactly 6 hours looks like it's a time zone problem. Once you've synchronized the two times, the problem should go away.

**Comment by azizs1** [comment]
Changing the MiR clock 6 hours ahead did the trick, thank you! However, it seems I had incorrectly assumed that this would resolve my issue with publishing to move_base_simple/goal as outlined in here, https://github.com/dfki-ric/mir_robot/issues/27. Just like the original poster on that issue thread, I can publish on /cmd_vel and move the MiR in real life, but it seems that when I try to input a specific pose as in https://github.com/dfki-ric/mir_robot/issues/27#issuecomment-486286245, nothing actually happens. Similarly, when I use the "2D Pose Estimate" RViz as in https://github.com/dfki-ric/mir_robot/issues/21, the robot is moved to the new pose on RViz but does not move at all in real life. The following is the `roswtf` output when I attempt to publishing the message to move_base_simple/goal:
![roswtf](https://user-images.githubusercontent.com/55463731/138193404-f4138ed1-d744-4143-b646-72cce60f75b1.png)
I do get the message that is "publishing and latching message" when I send the publish command, but nothing happens.
